---
- name: Checks environnement projet (placeholder)
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Print message
      ansible.builtin.debug:
        msg: "TODO: int√©grer checks cluster, kafka, webMethods, secrets, etc."
